### ISSUE TITLE
Installation instructions for Windows?

### ISSUE THREAD

**Issue by cloudgreen** [carderne/signal-export#10]
I'm sorry, but I don't really understand how to run this on Windows. Do I just install Python and then run this?

I would really appreciate if someone could write some installation instructions for Windows. It would be great if the instructions were easy and not assuming developer skills. 😀

Thank you so much!

**Comment by carderne** [comment]
Hi @cloudgreen sorry I don't have a Windows computer available to try it out. I would assume the best way would be something like this:
1. Download and install [Anaconda](https://www.anaconda.com/products/individual)
2. Run `conda install --file requirements.txt` from within the directory (or manually install each of the libraries listed in [requirements.txt](https://github.com/carderne/signal-export/blob/master/requirements.txt).
3. Run the script according to the instructions and hope for the best?

If you (or anyone else) get it working, please report back with what worked!

**Comment by BretW-Globant** [comment]
I did this on Windows through WSL, if you’re willing to use that. (But I also use WSL for other things already, so I understand that that’s not an acceptable answer for all).

**Comment by Absentity** [comment]
I did this on Windows through WSL, if you’re willing to use that. (But I also use WSL for other things already, so I understand that that’s not an acceptable answer for all).

**Comment by cloudgreen** [comment]
Thanks a lot for the input! I would like to run it with a minimum of time spent... I would guess maybe Anaconda is quicker than WSL, I don't know... 🤔

@Absentity Is it time-consuming to get WSL up and running and get the Python script to work there?

**Comment by franklin-be** [comment]
Hey, 
i got it working with with wsl2. (with wsl1 i had problems with loads of packages)
Just follow this tutorial to setup windows with wsl2: https://www.youtube.com/watch?v=IL7Jd9rjgrM (xrdp stuff not needed unless you wanna run signal-desktop on there too)

i also struggled with 18.04 so maybe get 20.04

Then follow the linux instructions here and potentially missing packages along the way.
