### ISSUE TITLE
RFE: uninstall instructions?

### ISSUE THREAD

**Issue by taw00** [carderne/signal-export#102]
For many of us, this script is a one-and-done process. I am relatively technical, but Docker is foreign to me. After we installed all of this, how do we rewind it all and pull it all back out?

Personally, I did this after a bunch of googling:
`docker system prune -a -f --volumes`
and then deleted the `signal-export-1.6.0` directory and archive.

Next, I will attempt to remove docker itself from my system (I'm a Fedora Linux guy who installed docker via RPMs and DNF, so it should be simple-ish). Not sure how easy (or complete) that will be just yet.

Is there anything else I should know about? Some config files somewhere or something?

Probably worth a paragraph or two.

Thanks. -t

**Comment by carderne** [comment]
This is a good point, will add it when I get some time.
Depending on what you already had installed, and what you downloaded, what you ran should do the job.

- Remove docker stuff: `docker system prune --all --volumes`
- Uninstall python package: `pip uninstall signal-export`
- Uninstall Docker: depends how you installed it
- Uninstall Python: ditto

**Comment by carderne** [comment]
Fixed in 63a9efa
