### ISSUE TITLE
Error: config.json not found in directory

### ISSUE THREAD

**Issue by seanwynwins** [carderne/signal-export#104]
**Desktop (please complete the following information):**
 - OS and version: [e.g. Ubuntu 22.04, Windows 11, WSL 2] MacOS Sonoma 14.1.1
- Terminal/shell used: [e.g. PowerShell, bash] iTerm, zsh

**Describe the bug**
Running

```
docker run carderne/sigexport --source ~/Library/Application\ Support/Signal/ --list-chats
```

this occurs:

```
Error: /Users/MyUser/Library/Application Support/Signal/config.json not found in directory /Users/MyUser/Library/Application Support/Signal
```

I've verified that the config.json exists at this path. I also tried giving read permissions to the relevant directories which didn't work.

**To reproduce**
Steps to reproduce the behavior. Please include the exact commands tried.
1. `docker run carderne/sigexport --source ~/Library/Application\ Support/Signal/ --list-chats`

**Comment by carderne** [comment]
Sorry that I never responded to this, I thought this would be some niggly user-specific thing but it's simply that you never mounted the volume. Docker doesn't have access to directories in your filesystem unless you specifically mount them.

Please follow the instructions here:
https://github.com/carderne/signal-export?tab=readme-ov-file#-no-python-install

**Comment by seanwynwins** [comment]
Thanks! Followed the instructions, `sigexport  ~/signal-chats` works now!
