### ISSUE TITLE
failing when I try to set the source

### ISSUE THREAD

**Issue by eville84** [carderne/signal-export#106]
- OS and version: Windows 11, WSL 2
- Terminal/shell used: PowerShell

**Description**
The software fails when I try to set the source. 

**To reproduce**
1. `docker run -v C:\Users\eville84\AppData\Roaming\Signal:/Signal -it python:latest bash`
2. `pip install signal-export`
3. `sigexport -lv --source /Signal`

after running the 3rd command the following outputs:

> Fetching data from /Signal/sql/db.sqlite
> 
> Using Docker to extract data, this may take a while the first time!
> Error: using Docker method, but is Docker installed?
> Try running this from the command line:
> docker run hello-world

**Comment by carderne** [comment]
Can you try the following:
1. Make sure you have the latest version installed `pip install signal-export==1.8.1`
2. Try running it without the `--source` flag: `sigexport -lv`
Get back to me if still no luck...

**Comment by eville84** [comment]
Thanks for getting back to me and thanks for all your efforts with this project. 
commands run:
`docker run -v C:\Users\eville84\AppData\Roaming\Signal:/Signal -it python:latest bash`
`pip install signal-export==1.8.1`
`sigexport -lv`

output:
`Error: /root/.config/Signal/config.json not found in directory /root/.config/Signal`

**Comment by eville84** [comment]
List of files in the container.  (it is mounting to the /Signal directory)
![image](https://github.com/carderne/signal-export/assets/7883613/07adc27b-7c0d-4149-a009-721b1df79ca7)

**Comment by eville84** [comment]
it may also be worth mentioning that im running signal 6.40.0 production.  I'm afraid of upgrading and loosing the conversation history. other devices with the same account have less conversation history.  I'm worried that will pass through if i upgrade

**Comment by carderne** [comment]
Hi are you still facing this issue? Seems like related to how you're trying to run the script...
I imagine you'll have more luck if you try one of the two methods suggested in the README, either use the script and let it manage Docker, or follow these steps:
https://github.com/carderne/signal-export?tab=readme-ov-file#-no-python-install

Closing this but if you can find a specific bug feel free to re-open it.
