### ISSUE TITLE
More precise timestamps

### ISSUE THREAD

**Issue by mitar** [carderne/signal-export#108]
It is possible to output more precise timestamps?

**Comment by mitar** [comment]
Yes, this is what I meant. So adding seconds.

I think it might be fine if we get JSON output. Then I can also format stuff myself.

**Comment by carderne** [comment]
Okay I'll close this in favour of #110.

**Comment by carderne** [comment]
Btw @mitar I ended up doing this for Markdown and HTML. Seconds are now included.

**Comment by mitar** [comment]
Looks great, thanks!
