### ISSUE TITLE
Add CSS stylesheet to the repo?

### ISSUE THREAD

**Issue by tjanez** [carderne/signal-export#11]
I see that the README mentions a CSS stylesheet:
https://github.com/carderne/signal-export/blob/34c89c959b968601a854a8de62782952c8c60d41/README.md#L18

but apparently it is ignored by git:
https://github.com/carderne/signal-export/blob/34c89c959b968601a854a8de62782952c8c60d41/.gitignore#L2

Hence, running `signal-export.py` reports:
```
Stylesheet (/tmp/signal-export/style.css) not found.You might want to install one manually at /tmp/signal-export-test/style.css.
```

**Comment by carderne** [comment]
Sorry, fixed in [Add stylesheet](https://github.com/carderne/signal-export/commit/ae1475150eed8b54470fb7bf3d8c746b07aee4bb)!

**Comment by tjanez** [comment]
Thanks!
