### ISSUE TITLE
Support exporting all messages into JSON

### ISSUE THREAD

**Issue by mitar** [carderne/signal-export#110]
I would like to backup all messages with all available metadata in some structured format like JSON, instead of lossy markdown. I would assume that internally data is in some structured form? So one could then have JSON -> Markdown -> HTML conversions. But I could also load JSON into some database and have them searchable, etc.

**Comment by carderne** [comment]
Yes this is a good idea... will try to look at this in the next couple of days but no promises.

**Comment by carderne** [comment]
Hi @mitar just added this in v2.0.0.
Please install it and give it a go:
```bash
pip install signal-export==2.0.0
```

Great to hear if there are any obvious bugs.

Btw: I could also just dump the full JSON that comes out of the DB but prefer to keep some control over what's coming out... if you just want the raw DB access, you can look at `sigexport/data.py` and see how you can run queries against that...

**Comment by mitar** [comment]
I tried it now and it works great! Thanks!
