### ISSUE TITLE
Error installing via pip - "Invalid requirement"

### ISSUE THREAD

**Issue by aleff-github** [carderne/signal-export#113]
**Desktop:**

- Windows 11
- cmd

**Describe the bug**

Error when I tried to install it via pip

**To reproduce**

Command:
`pip install 'signal-export[sql]'`

Error:
`ERROR: Invalid requirement: "'signal-export[sql]'"`

**Comment by carderne** [comment]
Oh this must be a Windows thing...
Try:
```bash
pip install signal-export[sql]
```
