### ISSUE TITLE
Could you please provide clear windows instructions for noobs?

### ISSUE THREAD

**Issue by Yolakalemowa** [carderne/signal-export#118]
**Is your feature request related to a problem? Please describe.**
Hi I'm a noob... 
I've been trying to understand the instructions and how to apply them to my Win10 machine situation but unable to... It's all very complicated.

I noticed many in the closed "issues" sections are also asking about Windows Instructions. Someone even said they might write instrucutions themself. 

Would it be possible to do that? It would be much appreciated I'm sure.

And thanks for an awesome tool... I can't wait to get it working.

**Comment by carderne** [comment]
@Yolakalemowa improved Windows instructions are now here:
https://github.com/carderne/signal-export/blob/main/INSTALLATION.md

**Comment by Yolakalemowa** [comment]
> @Yolakalemowa improved Windows instructions are now here: https://github.com/carderne/signal-export/blob/main/INSTALLATION.md

You guys are awesome! 

many not just me will find this very very helpful.

**Comment by Yolakalemowa** [comment]
Hello friend... 

wanted to export messages again before reinstalling signal. But the instructions aren't working for me. I think the same packages I have previously installed the first time still apply and are sitting there. So do I need to update anything or do the instructions not fit for me compared to a whole new first time install you think?

for example, the location suggested in windows instructions 
"cd C:\Users\<MyUserName>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.XX_<random-letters>\LocalCache\local-packages\Python3XX\Scripts\" 

do not fit for me. 

I couldn't find pythonsoftwarefoundation.python.3.xx_(random-letters) etc.
