### ISSUE TITLE
Even when using --manual flag: pysqlcipher3.dbapi2.DatabaseError: file is not a database

### ISSUE THREAD

**Issue by aaronkirkman** [carderne/signal-export#12]
I'm running `sigexport`  on [Debian under Windows](https://www.microsoft.com/en-us/p/debian/9msvkqc78pk6) with Python 3.7.3 (installed under Debian) and Signal v1.40.1 (installed under Windows). I installed `pysqlcipher3` with `pip3 install pysqlcipher3` and ran this command:

    python3 sigexport.py --source "/mnt/c/Users/ak/AppData/Roaming/Signal/" --manual --overwrite outputdir

throws this exception:

```
Error: near line 1: file is encrypted or is not a database
Traceback (most recent call last):
  File "sigexport.py", line 489, in <module>
    main()
  File "/home/ak/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ak/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ak/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ak/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "sigexport.py", line 477, in main
    convos, contacts = fetch_data(db_file, key, manual=manual, chat=chat)
  File "sigexport.py", line 182, in fetch_data
    c.execute(query)
pysqlcipher3.dbapi2.OperationalError: no such table: conversations
```

If I take the key from the config.json file (prepending `0x` to it), and browse the db.sqlite manually, I can see the table `conversations` in it. It's the decryption that isn't working because the db-decrypt.sqlite file is empty.

**Comment by carderne** [comment]
I don't know how this works with WSL/Windows, but please try following the **For Linux** instructions in the **Installation** part of the README.

**Comment by carderne** [comment]
Feel free to re-open this issue!

**Comment by carderne** [comment]
Hi @anon8675309 a pull request would be great!

**Comment by floe** [comment]
JFYI, if you don't want to clutter your `/usr/local/` folder with spurious library installations (a recipe for disaster sooner or later), then you can build sqlcipher, but skip `sudo make install` and just run `LD_LIBRARY_PATH=/path/to/sqlcipher/.libs sigexport --list-chats`.
