### ISSUE TITLE
Misspelling for macOS instructions

### ISSUE THREAD

**Issue by javentous** [carderne/signal-export#121]
**Desktop (please complete the following information):**
 - OS and version: macOS Sonoma 14.5
- Terminal on macOS

**Describe the bug**
Missed a parentheses

**To reproduce**
Use the following command:
```
export C_INCLUDE_PATH="$(brew --prefix sqlcipher)/include"
export LIBRARY_PATH="${brew --prefix sqlcipher)/lib"
                     ^^^
```

**Fix**
Change the curly brace in LIBRARY_PATH to a parentheses:
```
export C_INCLUDE_PATH="$(brew --prefix sqlcipher)/include"
export LIBRARY_PATH="$(brew --prefix sqlcipher)/lib"
```

**Comment by carderne** [comment]
thanks, fixed
https://github.com/carderne/signal-export/commit/d7bb3e7bd124f0a95d4ae8703ccdb97472a793d8
