### ISSUE TITLE
TypeError: style() got an unexpected keyword argument 'gf'

### ISSUE THREAD

**Issue by tipyn** [carderne/signal-export#125]
**Desktop (please complete the following information):**
 - OS and version: [e.g. Ubuntu 22.04, Windows 11, WSL 2]

macOS 14.4 (23E214)

- Terminal/shell used: [e.g. PowerShell, bash]

zsh

**Describe the bug**

https://hastebin.skyra.pw/emumejunin.pgsql

**Comment by carderne** [comment]
You're on an old version, could you please upgrade it
```
pip install -U signal-export
```

and try again?
