### ISSUE TITLE
Note to Self not exporting

### ISSUE THREAD

**Issue by amashari** [carderne/signal-export#129]
**Desktop (please complete the following information):**
 - OS and version: [e.g. Ubuntu 22.04, Windows 11, WSL 2]
- Terminal/shell used: [e.g. PowerShell, bash]

**Describe the bug**
Using docker installation. Worked beautifully and very straight forward. Thank you. The only issue was that that "Note to Self" chat does not export, either with the general command for exporting everything or with sigexport --chats="Note to Self" ~/signal-chats which generates an empty folder.

**Comment by amashari** [comment]
My mistake. It does export but under my own name not "Note to Self".

**Comment by trkohler** [comment]
> It does export but under my own name not "Note to Self".

I have the similar issue (https://github.com/carderne/signal-export/issues/172), there is a folder with my name being created, but amount of messages is not correct (just 2, instead of hundreds).
