### ISSUE TITLE
Problem with backup chats

### ISSUE THREAD

**Issue by Raikkok** [carderne/signal-export#130]
Hi everyone. I have next issue:

iOS 17.5.1 
Signal APP iOS 7.16 (162)

Signal Desktop Windows x64 7.14.0

both devices are linked through QR.

But i only have one chat with one person.. and when I try to backup.. in the desktop app shows next message:

"For your security, the historial chat won´t be transfered to new devices linked"

So.... Is there any way to "rescue" export in windows the chat in signal ios??

All is well installed, docker desktop, enabled vitual machine in bios, latest version of python, etc..

The only thing I saw.. is make tons of screenshots, joint them with picsew and after that ... pass to OCR from photo to text.. but 3 months of conversation is a torture....

Thanks in advanced

**Comment by carderne** [comment]
Signal Desktop doesn't get your old chats, just new ones since you activated it. Nothing signal-export can do to help you.
