### ISSUE TITLE
zsh: command not found: sigexport

### ISSUE THREAD

**Issue by frigeky00** [carderne/signal-export#134]
**Desktop (please complete the following information):**
 - OS and version: macOS Sonoma
- Terminal/shell used: terminal, zsh

**Describe the bug**
Following instructions, I enter `sigexport --no-use-docker ...` but the terminal replies `zsh: command not found: sigexport`

**To reproduce**
1. On macOS Sonoma, open the terminal
2. Type `brew install openssl sqlcipher` (update brew in the process)
3. Type `export C_INCLUDE_PATH="$(brew --prefix sqlcipher)/include"` and `export LIBRARY_PATH="$(brew --prefix sqlcipher)/lib"`
4. Install signal-export with `pip3 install 'signal-export[sql]'` (pip gives `zsh: command not found: sigexport`, not the first time)
5. Type `sigexport --no-use-docker ...`

**Comment by carderne** [comment]
Try:
```bash
python -m sigexport
```

**Comment by carderne** [comment]
Try python3 or something else, but you’ll have to figure that out yourself.
