### ISSUE TITLE
pysqlcipher3 vs pysqlcipher3static vs sqlcipher3-wheels

### ISSUE THREAD

**Issue by maxhbr** [carderne/signal-export#137]
Hey,

I am trying to get signal-export packaged for me on [NixOS](https://nixos.org/). Sadly [neither `pysqlcipher3static` nor `sqlcipher3-wheels` are already available](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=sqlcipher3).

* https://github.com/carderne/signal-export/releases/tag/v3.0.2 uses [`sqlcipher3-wheels`](https://github.com/laggykiller/sqlcipher3) but is not yet promoted to be a release
* https://github.com/carderne/signal-export/releases/tag/v3.0.1 uses [`pysqlcipher3static`](https://github.com/carderne/pysqlcipher3static/)

I would like to understand where to invest work. Is already decided which dependency will be used in the end?

**Comment by carderne** [comment]
These are all the libraries I'm aware of:
1. [leapcode/pysqlcipher](https://github.com/leapcode/pysqlcipher/) Python 2.x only
2. [rigglemania/pysqlcipher3](https://github.com/rigglemania/pysqlcipher3/) fork of (1) with Python 3.x support. What signal-export used until recently.
3. [carderne/pysqlcipher3static](https://github.com/carderne/pysqlcipher3static) fork of (2) with binary wheels added

4. [coleifer/sqlcipher3](https://github.com/coleifer/sqlcipher3) not sure how this relates to (1)
5. [laggykiller/sqlcipher3](https://github.com/laggykiller/sqlcipher3) ([sqlcipher3-wheels](https://pypi.org/project/sqlcipher3-wheels/) on PyPI) fork of (4) with binary wheels

I built (3) before I became aware of (5), which was created a few months ago. It has binary wheels for Windows, which are quite tricky to create in this instance. So I switched to that. I have no intention to switch again.

**Comment by maxhbr** [comment]
> I have no intention to switch again.

Thanks

**Comment by maxhbr** [comment]
FYI: as sqlcipher3-wheels uses conan for building, it will be hard to get it working on NixOS. There are two not yet successful lengthy discussions https://github.com/NixOS/nixpkgs/issues/94555 and https://github.com/NixOS/nixpkgs/issues/186570.
