### ISSUE TITLE
Merging with backup from old version not working

### ISSUE THREAD

**Issue by ExecutiveCodingProducer** [carderne/signal-export#138]
**Desktop (please complete the following information):**
 - OS and version: Ubuntu 22.04

**Describe the bug**
So far I have been using a version of the script which I downloaded in May 2023 and have merged the backups several times since then. Today I wanted to run another backup but it failed due to the new database encryption from Signal.

Using the provided workaround ("secret-tool lookup application Signal") I was able to get the current version running after installing using the "pip install signal-export" command.

However, the merge crashes with the following error message:

.local/lib/python3.10/site-packages/sigexport/models.py:155 in   │
│ <listcomp>      
....
TypeError: Reaction.__new__() missing 1 required positional argument: 'emoji'

Is there any way to deal with this or do I have to use the new version and keep the old backup seperately?

Thanks!

**Comment by carderne** [comment]
Should be fixed now in `v3.1.1`

```
pip install signal-export>=3.1.1
```
