### ISSUE TITLE
WARNING: typer 0.12.3 does not provide the extra 'all'

### ISSUE THREAD

**Issue by pro-sumer** [carderne/signal-export#140]
**Desktop (please complete the following information):**
 - macOS Sonoma 14.6.1
- iTerm 2 Build 3.5.4, zsh 5.9

**Describe the bug**
```
WARNING: typer 0.12.3 does not provide the extra 'all'
```

**To reproduce**
Run `pip3 -q install -r requirements.txt --upgrade` with this requirements.txt contents:
```
signal-export
pysqlcipher3
```

**Possible solution**
Use `typer ~= 0.12` instead of `typer[all] ~= 0.7` in `pyproject.toml`?

See https://github.com/fastapi/typer/discussions/785

**Comment by carderne** [comment]
Thanks, this is fixed and released as v3.1.2
```bash
pip install signal-export>=3.1.2
```
