### ISSUE TITLE
broken password retreival on gnome and kde

### ISSUE THREAD

**Issue by belamu** [carderne/signal-export#147]
**Desktop (please complete the following information):**
 - OS and version: gnome and kde

**Describe the bug**
See https://github.com/carderne/signal-export/pull/146#issuecomment-2458828503
"Failed to decrypt password."

**To reproduce**
Run without --password

**Comment by carderne** [comment]
Is this related to your PR #146? Is this a regression? Appreciate if you could throw up a fix!

**Comment by belamu** [comment]
See #148 for fix.
