### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by hahyes** [carderne/signal-export#20]
Hi there.

I'm trying to run sigexport.py but syntax error is occuring.

First error:
```
File "C:\signal-export\signal-export\sigexport.py", line 46
    print(f"\tCopying attachments for: {name}")
```

It was only log, so I got rid of this line in code. After that another error occured:

```
File "C:\signal-export\signal-export\sigexport.py", line 62
    ] = f"{date}_{i:02}_{att['fileName']}".replace(
```

At this point I don't know, what is going on.

I'm using Python 3.7, if it is important.

**Comment by carderne** [comment]
Seems like an f-string issue, which were introduced iirc in Python 3.6.

Are you sure the script is being run with python 3.7?

Try `python3 ./sigexport.py ...` to make sure.

Also try this to check the version and make sure f-strings work:
```
python3 -c 'import sys;print(f"{sys.version}")'
```
