### ISSUE TITLE
Import function? :)

### ISSUE THREAD

**Issue by MatejKovacic** [carderne/signal-export#25]
Hi, thank a lot for this program. It is a real life saver! I had a problem with old data - I reinstalled app on iPhone and of course lost all the history on the phone. But Signal Desktop was also unable to sync with new installation... So I had to remove data directory and reinstall Signal Desktop.

However, I made a copy of Signal directory with the data and now I was able to restore old messages thanks to you.

But I am wondering... would it be possible to import the exported and merged messages to a current Signal Desktop database? In that case, I would be able to "restore" my old conversations.

I know this is opening a completely new set of problems, but can you just try to consider this idea?

**Comment by franklin-be** [comment]
if you have the previous signal desktop installation folder..  replacing current one with that one should work. then go to your signal app on the phone and unlink all desktop apps. Now start your desktop app and it should ask you to re authenticate. The messages in the db should be kept and will continue to be written in the same db.  this procedure worked for me for moving a signal desktop db from pc a to pc b.

**Comment by MatejKovacic** [comment]
No, unfortunately it does not work. Actually, I tried to re-register signal on a phone, but it crashed completely, so I uninstalled it and installed it again.
Then Signal Desktop told me, that is is unable to sync, and that I need to remove database completely. That is when I did a backup.

After fresh installation on both devices, Signal started to work, but I lost my message history. Fortunately, I was able to export it with this app.

What is also weird is, that my contacts now can see old message thread with me, but cannot send me a message through that thread. If I contact them again (open new thread), we can have a conversation on a new thread. Really annoying situation, because if I do not contact them first, they just see the old conversation with me and their Signal notifies them that this contact is not available anymore or sth. like this.

BTW, the main reason why I decided to reinstall Signal on the phone is that notifications were not working. Several people reported this bug, but it seems that for developers is more important we get new sticker pack than to be able to get notifications properly... I wrote an extensive bug report... well, it was rant :) but it seems that Signal developer's priorities are elsewhere.

Sorry for a little bit longer post, but in short, the solution you proposed does not work for me.

**Comment by carderne** [comment]
If what you mean is restoring messages exported using this tool *back into* the Signal desktop database, then unfortunately not completely possible with the current exported data, as it only exports a subset of all the data in the Signal database.

That said, it should be possible to write some code in the future to do this, and it could be worth looking into… But they make no guarantees about database schema stuff and there’s quite a bit of cruft so it might not be easy to keep it working.

**Comment by MatejKovacic** [comment]
I totally understand this. It is just a wish, and I know there are not a lot of fairies in real world... :)

**Comment by carderne** [comment]
Closing this issue but feel free to re-open if needed.
