### ISSUE TITLE
Export is empty

### ISSUE THREAD

**Issue by MichaelDim02** [carderne/signal-export#33]
The output seems normal:
```
Copying and renaming attachments
Creating markdown files
Creating HTML files
Done! Files exported to export_dir
```
No error messages. I've also checked the permissions.
The export_dir is empty, except for the stylesheet.

I'm using Linux and my Signal account is based on an android phone. Any ideas what the problem could be?

**Comment by MichaelDim02** [comment]
Sure. Not much of a change, though.

`Fetching data from /home/michael/.config/Signal/sql/db.sqlite


Copying and renaming attachments

Creating markdown files

Creating HTML files

Done! Files exported to signal_export.
`
The sqlite file is there.

**Comment by carderne** [comment]
Sorry @MichaelDim02, I wrote a reply to this but apparently never sent it.

1. Comment out these lines: https://github.com/carderne/signal-export/blob/c4bb6492d39f113370f1824086c3e6c7dc9e452c/sigexport/main.py#L266-L267
2. Run the script with the `--manual` flag.
3. There should now be a file called `db-decrypt.sqlite` in the same location as the original.
4. Try open *that* file in sqlitebrowser et al!

**Comment by carderne** [comment]
You could also try these steps: https://github.com/carderne/signal-export/issues/26#issuecomment-906504795
