### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by chapochn** [carderne/signal-export#40]
Hello,

I tried to install on Mac using the docker method.

When I run:
```
docker run --rm -it --name signal-export \
  -v ${SIGNAL_INPUT}:/Signal \
  -v ${SIGNAL_OUTPUT}:/output \
  carderne/signal-export:latest
```

I get:
`Error: /tmp/Signal/config.json not found in directory /tmp/Signal`

Any ideas?
Thank you!

**Comment by carderne** [comment]
Two possibilities I think:

1) You didn't set the environment variables. In that case, run the following (I've also made the README a bit more clear).
```bash
SIGNAL_INPUT="~/Library/Application Support/Signal" 
SIGNAL_OUTPUT=~/Documents/output
docker run --rm -it --name signal-export \
  -v ${SIGNAL_INPUT}:/Signal \
  -v ${SIGNAL_OUTPUT}:/output \
  carderne/signal-export:latest
```

2) Docker has pulled a slightly outdated version of the image, in which case try the following (still making sure the env vars above are set!). Note the added option `--pull=always`.
```bash
docker run --rm --pull=always -it --name signal-export \
  -v ${SIGNAL_INPUT}:/Signal \
  -v ${SIGNAL_OUTPUT}:/output \
  carderne/signal-export:latest
```

**Comment by chapochn** [comment]
Thanks for the quick response!

I need to put:
`SIGNAL_INPUT=~/Library/Application\ Support/Signal`
because
`SIGNAL_INPUT="~/Library/Application Support/Signal"`
gives errors.

This worked:
```
docker run --rm --pull=always -it --name signal-export \
  -v ${SIGNAL_INPUT}:/Signal \
  -v ${SIGNAL_OUTPUT}:/output \
  carderne/signal-export:latest
```

Thank you!

Lots of gratitude for coding and publishing this!
