### ISSUE TITLE
Stickers are not exported 

### ISSUE THREAD

**Issue by yringot** [carderne/signal-export#44]
Stickers are not being exported, resulting in empty messages like so:
![image](https://user-images.githubusercontent.com/3494882/148227121-6251ace4-d44d-4b31-895a-04ab8af599d8.png)

Would it be possible to export and displa them as well?

**Comment by carderne** [comment]
Stickers are now exported as the emoji they represent.

I've never used a sticker so not sure if that will always work?

https://github.com/carderne/signal-export/commit/a4dd8fffe08ecc06bf6051589e38d726b7f33dd1

**Comment by yringot** [comment]
Simpler emoji like 💕 are indeed exported into the chat. But actual stickers like 
![image](https://user-images.githubusercontent.com/3494882/148241420-477b3ab7-5cfa-4976-a97c-060cb1debb8e.png) or 
![image](https://user-images.githubusercontent.com/3494882/148241782-c806198a-421e-4f41-8426-ac20209ce577.png)
 turn up as empty messages. It could be because inside the sticker pack there is no emoji associated with them. Or it could be some other cause.

**Comment by yringot** [comment]
... aaand I should have paid more attention. They are indeed being converted to emojis, which is a good start.

![image](https://user-images.githubusercontent.com/3494882/148273880-ab7ddbf5-3856-45eb-b842-c1479029542c.png)

Do you think it's possible to access  the stickers, convert them into pngs and insert them in place of the emojis?

**Comment by carderne** [comment]
When I looked at this, it was just sticker pack identifiers or some such that were coming along with the JSON, so I think it would be much too difficult to try to figure out how to reverse that back into a sticker... Closing this as not a priority, but feel free to re-open if you have ideas.
