### ISSUE TITLE
"@" mentions of group members not written out

### ISSUE THREAD

**Issue by yringot** [carderne/signal-export#45]
When a group member is mentioned (e.g. @yringot), the mention is translated into this in the markdown and also the HTML:

![image](https://user-images.githubusercontent.com/3494882/148275289-1d11dd25-f08c-4279-874b-de800c178aac.png)

The Unicode character is ￼ (U+FFFC). For me it's a minor bug because most of my chats are 1v1 but it might be interesting for other people.

**Comment by yringot** [comment]
Maybe this is connected to how "New Groups" are handled differently? (See issue #46 )

**Comment by carderne** [comment]
Had a look at this, and the `@`ed part of the conversation is just empty in the raw text from the database... Not really sure how to deal with that.

Becoming impossible to keep up with the database schema, I wish they'd just build a native backup/export solution!

**Comment by yringot** [comment]
Fully agree... It's a bit infuriating. Thank you for your hard work!
