### ISSUE TITLE
Image file html code does not match actual source filename

### ISSUE THREAD

**Issue by elkrojo** [carderne/signal-export#48]
Images are not being displayed

**Comment by carderne** [comment]
Can you clarify or provide some examples?

**Comment by elkrojo** [comment]
attribute `src="./media/2021-02-22T18:23:51.829000_00_signal-2021-02-22-162728.jpeg"`

actual image file: 2021-02-22T18/23/51.829000_00_signal-2021-02-22-162728.jpeg

Developers must have changed the timestamp separator from colon to slash during a recent update.

**Comment by carderne** [comment]
Can you please confirm that you're using the latest code/Docker image, and share the exact command you used? The filenames should have neither slashes nor colons in them.

https://github.com/carderne/signal-export/blob/e4aa05d519d13944031b623852aed682e3d6d69b/sigexport/main.py#L71-L76
