### ISSUE TITLE
Docker issue config.json

### ISSUE THREAD

**Issue by vinnytroia** [carderne/signal-export#52]
Hi. I am trying to load the docker image and I keep getting: 
/Signal/config.json not found in directory /Signal

I'm not sure where it is looking for this config file. I have tried setting env variables with the input and output paths but that doesn't seem to help. 

I am running Mac 12.1

Thanks

**Comment by carderne** [comment]
Please share the exact commands you entered. And make sure that there _are_ actually Signal files in the directory you set as `SIGNAL_INPUT`.

**Comment by vinnytroia** [comment]
Which environment do you set these variables? I also replaced the variable names with the full path on my computer /users/name/library, etc
Can’t I edit this after the docket is launched ?


 Vinny Troia, PhD

 Founder, Head of Research // ShadowByte

 M: (314)-944-1944 | W: shadowbyte.com<https://www.shadowbyte.com/>


________________________________

**Comment by carderne** [comment]
Hi @vinnytroia I can't help if you don't share the command you entered.

These are the environment variables:
```bash
SIGNAL_INPUT=~/Library/Application Support/Signal
SIGNAL_OUTPUT=~/Downloads/signal-output
```

They are substituted in when you run the script:
```bash
docker run --rm -it --name signal-export \
  -v ${SIGNAL_INPUT}:/Signal \
  -v ${SIGNAL_OUTPUT}:/output \
  carderne/signal-export:latest
```

An alternative is to just enter them in directly without the env vars:
```bash
docker run --rm -it --name signal-export \
  -v ~/Library/Application Support/Signal:/Signal \
  -v ~/Downloads/signal-output:/output \
  carderne/signal-export:latest
```

**Comment by vinnytroia** [comment]
Sorry, re-visiting this. This SHOULD work, but i keep getting: docker: invalid reference format: repository name must be lowercase. 
WHich is strange because everything is lowercase except for the path info.
