### ISSUE TITLE
Error: /Signal/config.json not found in directory /Signal (`flatpak` install)

### ISSUE THREAD

**Issue by dbitouze** [carderne/signal-export#54]
# Context
- `Linux Mageia` 8
- `Signal Desktop App` 5.32.0 (`flatpak` install)

# Issue
When I run:
```
$ SIGNAL_INPUT=~/.config/Signal
$ SIGNAL_OUTPUT=~/Downloads/signal-output
$ docker run --rm -it --name signal-export \
  -v ${SIGNAL_INPUT}:/Signal \
  -v ${SIGNAL_OUTPUT}:/output \
  carderne/signal-export:latest
```
I get: `Error: /Signal/config.json not found in directory /Signal`.

I suspect this comes from the `flatpak` install which doesn't create any `~/.config/Signal` directory but I couldn't find any equivalent folder.

**Comment by carderne** [comment]
Just searched and according to [this](https://docs.flatpak.org/en/latest/flatpak-command-reference.html), the data might be stored at: `$HOME/.local/share/flatpak/`. Have a look around and see if you can find it. I don't use Flatpak.

**Comment by dbitouze** [comment]
Unfortunately:

```
$ tree ~/.local/share/flatpak/          
/home/bitouze/.local/share/flatpak/
├── db
└── repo
    ├── config
    ├── extensions
    ├── objects
    ├── refs
    │   ├── heads
    │   └── remotes
    ├── state
    └── tmp
        └── cache
```

**Comment by carderne** [comment]
What about [this](https://www.ctrl.blog/entry/backup-flatpak.html)? Anyway good luck, let me know if you find it.

**Comment by dbitouze** [comment]
Good catch! Everything worked smoothly with:
```
$ SIGNAL_INPUT=~/.var/app/org.signal.Signal/config/Signal
$ SIGNAL_OUTPUT=~/Downloads/signal-output
$ docker run --rm -it --name signal-export \
  -v ${SIGNAL_INPUT}:/Signal \
  -v ${SIGNAL_OUTPUT}:/output \
  carderne/signal-export:latest
```
Thanks!
