### ISSUE TITLE
Readlink illegal option error on MacOS when running the helper script

### ISSUE THREAD

**Issue by vonknio** [carderne/signal-export#55]
Looks like the MacOS `readlink` does not support the `f` option. This is the error when running the `signalexport` function from helper.sh:

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

Using MacOS 12.1.

**Comment by carderne** [comment]
Can you check if `realpath` works?
Eg:
```bash
realpath ~/Documents/path/to/directory
```

It should print the full directory without the tilde `~`.

**Comment by carderne** [comment]
This was fixed/changed in https://github.com/carderne/signal-export/commit/2c29b9f969f7505d8808c376601e4a90909c34c2
