### ISSUE TITLE
Not exporting up to very latest chats

### ISSUE THREAD

**Issue by hamensman** [carderne/signal-export#57]
Using Arch Linux. Installed docker. I set the appropriate environmental variables. (In other words, doing the `Easy mode (maybe?): Docker` method)

Ran this:
```
docker run --rm -it --name signal-export \
  -v ${SIGNAL_INPUT}:/Signal \
  -v ${SIGNAL_OUTPUT}:/output \
  carderne/signal-export:latest
```

All the chats of my conversations were exported, but only up to a certain date - where they stop varies between contacts.

For example, a conversation with one contact started (visible to signal-desktop) on October 30 2021. The export **should** show from that to February 19 2022. But it only shows from October 30 2021 to December 31 2021.

Is there some kind of limit which `signal-export` can export chats? And thus an expected occurrence? Or am I overlooking something?

**Comment by carderne** [comment]
Have you checked that Signal Desktop is up to date with what’s on your phone? There is no filtering n `signal-export`.

**Comment by hamensman** [comment]
Yes - signal-desktop is indeed update to date with my phone.

**Comment by carderne** [comment]
Weird… first step is to add the `—verbose` flag and see if anything interesting pops up.  After that you might have to try add some `print` statements in strategic spots to see if you can figure out what’s going on!

**Comment by hamensman** [comment]
I figured it out now. Had to use the `--paginate 0` flag!
