### ISSUE TITLE
brew postinstall ca-certificates fails macOS

### ISSUE THREAD

**Issue by fsfra** [carderne/signal-export#59]
Hi, as the title says, when I try to instal sqlciphr on my M1 Mac running macOS 12.3 the install fails at the regenerating ca certificates section. 

Manually starting:

% brew postinstall ca-certificates         
==> Postinstalling ca-certificates
==> Regenerating CA certificate bundle from keychain, this may take a while...

it just sits there for hours. 

Any ideas?

Thanks for putting this tool together, I hope to be able to use it soon.

**Comment by carderne** [comment]
Hi @fsfra sorry I've actually never tried installing any of this on macOS. Would recommend the Docker method.

Let me know if you got it working (and how), will close this otherwise.
