### ISSUE TITLE
Missing module "markdown"

### ISSUE THREAD

**Issue by Absentity** [carderne/signal-export#6]
I don't have a lot of experience with Python, but when I followed the steps in the readme for Linux (though I'm using WSL), I get the following error:

```
$ python3 ./sigexport.py --manual ../../Desktop/signalbackup
Traceback (most recent call last):
  File "./sigexport.py", line 13, in <module>
    import markdown
ModuleNotFoundError: No module named 'markdown'
```

I fixed this by running the following before re-running the project:
```
$ pip3 install markdown
```

Is this the correct step? Is there something that can be added to `requirements.txt` for a more likely successful "out of box" experience?

**Comment by carderne** [comment]
Hi @Absentity thanks for noticing this! Have just added `markdown` to `requirements.txt`.

**Comment by tjanez** [comment]
Hi, @carderne!

I still don't see `markdown` in `requirements.txt`:
https://github.com/carderne/signal-export/blob/f8ba2783d640e919ba43b8ee8ce9183c2fc6f1b2/requirements.txt#L1-L3

**Comment by carderne** [comment]
Wow sorry don't know what happened there. Added now!

**Comment by tjanez** [comment]
> Wow sorry don't know what happened there. Added now!

No worries, thanks!
