### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'dict' and 'float'

### ISSUE THREAD

**Issue by rudyrichard** [carderne/signal-export#61]
When running `signalexport output`
During the step: "Creating markdown files"

_**Terminal outputs this:**_ 
```pytb
Traceback (most recent call last):
  File "/usr/local/bin/sigexport", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/sigexport/main.py", line 657, in cli
    run(main)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 864, in run
    app()
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/sigexport/main.py", line 644, in main
    make_simple(dest, convos, contacts, quote)
  File "/usr/local/lib/python3.9/site-packages/sigexport/main.py", line 128, in make_simple
    date = datetime.fromtimestamp(timestamp / 1000.0).strftime(
TypeError: unsupported operand type(s) for /: 'dict' and 'float'
```
**_Current behaviour:_** 
All media folders are being created and populated. The media extraction seems to be complete.
No conversations nor text is present in any of the folders 

**_System:_** 
Mac M1, Monterey, running on Docker. 

Thanks for putting this tool together! This is saving me A LOT of time!

**Comment by carderne** [comment]
Hi @rudyrichard,

Are you running use Docker or a local Python install?

If the latter, could you try adding the following (the green lines) to line 128 of `sigexport/main.py` and then run it again to share what you get. This will help me understand what's going on!

(If you _aren't_ using Docker, then I'll just add an error check to ignore whatever is happening there.)

```diff
diff --git a/sigexport/main.py b/sigexport/main.py
index 0746007..531a2ee 100755
--- a/sigexport/main.py
+++ b/sigexport/main.py
@@ -125,6 +125,8 @@ def make_simple(dest, conversations, contacts, add_quote=False):
                     secho("\t\tNo timestamp or sent_at; date set to 1970")
                 date = "1970-01-01 00:00"
             else:
+                if isinstance(timestamp, dict):
+                    print(timestamp)
                 date = datetime.fromtimestamp(timestamp / 1000.0).strftime(
                     "%Y-%m-%d %H:%M"
                 )
```

**Comment by rudyrichard** [comment]
Hey Chris, thanks for the fast reply! 
unfortunately I'm using Docker.. have not been able to install local python. 
Anything I can try instead?

**Comment by carderne** [comment]
## NB
If the follow is too much effort, out of your comfort zone, please just let me know and I'll just write a simple fix for the script.

## How to edit the script inside the Docker container
If you have the time/inclination, please try this. First run the Docker image as follows. (This adds some commands to enter into the container with a shell prompt.)
```bash
docker run --rm -it --name signal-export  \
    --pull=always \
    -v ~/.config/Signal:/Signal \
    -v ~/Downloads/output:/output \
    --entrypoint=bash \
    carderne/signal-export:latest
```
Then depending on whether you prefer Vim or Nano (or something else), run the following **inside the Docker shell you've just been presented**:
```bash
apt update && apt install vim
# or
apt update && apt install nano
```

And edit the file `/signal-export/sigexport/main.py` using whichever editor you intsalled, making the change as I suggested above.

And finally, run the following (still inside the Docker container):
```bash
python /signal-export/sigexport/main.py --source=/Signal /output/test
```

And hopefully you'll get some extra output about the weird timestamp that's popping up!

**Comment by rudyrichard** [comment]
Hey Chris,
Thanks for the detailed instructions, I have tried over the last few days
to make it work but I think this is officially out of my reach. Please let
me know if you end up making a fix for this so I can update and run. Thanks
a lot in advance

**Comment by carderne** [comment]
No worries. Your issue should be fixed now by https://github.com/carderne/signal-export/commit/216451658aa1b3daf856fdc0d477490857097b94.

Try running your original command again, adding `--pull=always` after `docker run...`.

**Comment by rudyrichard** [comment]
incredible - it works. THANKS SO MUCH!
