### ISSUE TITLE
secho doesn't work on terminal with manual sqlcipher

### ISSUE THREAD

**Issue by artelse** [carderne/signal-export#66]
On line 228, `secho` is not a terminal command, so the manual `sqlcipher` fails.
Can this be changed to `echo`?
Thanks.

**Comment by carderne** [comment]
Oops this is a huge bug, sorry I left it for so long! Fixed now in https://github.com/carderne/signal-export/commit/06426c0bd67ae0df32ee3b3333200d20d5cb6f87
