### ISSUE TITLE
Feature request: only create backup for active chats

### ISSUE THREAD

**Issue by artelse** [carderne/signal-export#67]
I see there is the option to create a list of chats that can be backed up. This is asking active work on our part. Isn't it more practical to check if a contact has ever engaged in a chat and only backup those? Now we end up with a huge list of non-chat directories. I switched on logging and see it shouldn't be hard to implement a filter.
BTW: thanks for this great piece of essential software.

**Comment by carderne** [comment]
Hi @artelse sorry for the huge delay, haven't had much time.

This is a great idea, will try to implement it in the next week or two.

(Or feel free to submit a PR!)

**Comment by carderne** [comment]
Have implemented this in https://github.com/carderne/signal-export/commit/ff899cf3067c4c9136c900139623d3ce50be16d9.

Let me know how it works for you.

**Comment by artelse** [comment]
Cool, just tested it out after fixing [pysqlcipher3](https://github.com/rigglemania/pysqlcipher3/issues/26) and it works fine. Thanks!
