### ISSUE TITLE
No output using the Docker method

### ISSUE THREAD

**Issue by TheCorp** [carderne/signal-export#68]
So I used the Docker method which seemed to work smoothly, I also used the helper.sh method to make it easier. I see no output though despite what seems to be a clean run... No output to be found... Am I doing something wrong here?

```signalexport signal_backup/
-bash: realpath: command not found
Copying and renaming attachments
Creating markdown files
Creating HTML files
Done!

**Comment by carderne** [comment]
Hi @TheCorp sorry that I'm only responding now.

If you can share the following details I can try to help you:
1. Your OS/version and whether you're using WSL or anything like that
2. What terminal/shell you're using
3. What command(s) you tried running.

**Comment by TheCorp** [comment]
No problem at all, I know this is a small side project!

1. Mac OS Monterey 12.4
2. iTerm2 / Bash (yes not the zsh default for 12.4)
3. I tried using the helper.sh thing so I was running `signalexport output --chats=SomeChatName` and the output is consistently what I listed in the original comment above. I can tell its actually _doing_ something because when I don't specify a chat it runs for longer but I never see any output.

Any tips? Should I just go back and try the direct Docker method? ie something like this?
```docker run --rm -it --name signal-export \
  -v "$SIGNAL_INPUT:/Signal" \
  -v "$SIGNAL_OUTPUT:/output" \
  carderne/signal-export:latest --overwrite --chats=Jim```

**Comment by TheCorp** [comment]
Ahhh man, I am very dumb. I had not set the env variables! I somehow missed that step. Maybe a better warning or error there would help the dummies like me. I got it working when trying to run the actual direct Docker commands rather than going directly to the helper.

That being said, the helper still doesn't work, not sure why. I can try and mess around with that again if you can't think of anything. Maybe something to do with the `"realpath" command not found` part?

**Comment by carderne** [comment]
Can you try changing `helper.sh` as follows and see if it works. (Baiscally, replace `realpath` with `readlink -f`.)
```diff
- output=$(readlink -f $1)
+ output=$(realpath $1)
```

I had a report #55 that `readlink` doesn't work, but some Googling suggests its more likely to work than `realpath`.

(Don't forget to resource the script afterwards `source helper.sh`).

**Comment by carderne** [comment]
Actually have a better solution. I just https://github.com/carderne/signal-export/commit/2b9ea75a7f3ee4e1d184920137503096a27db52c updated the `helper.sh` script to avoid the `realpath` issue.

Download/pull the latest version and try it out!

**Comment by TheCorp** [comment]
Huzzah, it works! Thanks man, this is great. Appreciate the extended help. 

What's the best way to do feature requests? I think my only request at this point is to have a single page of full output of each chat (maybe separate from the paginated version) to make it easier to search. Not a huge issue regardless. Thanks again.

**Comment by carderne** [comment]
You can add `-p 0` to get a non-paginated version.
