### ISSUE TITLE
export crashes with a RecursionError

### ISSUE THREAD

**Issue by reludy** [carderne/signal-export#69]
**Desktop (please complete the following information):**
 - OS and version: MacOS 12.3.1
 - Macbook Pro 2021 (M1 Pro 16GB)
- Terminal - zsh (?)
- My signal messages are all with ONE person only, and the app on my phone takes about 10 gigabytes.

**Describe the bug**
The program manages to copy and rename all attachments, crashes half way into creating HTML files, with the error "RecursionError: maximum recursion depth exceeded while calling a Python object".

**To reproduce**
1. Followed the Easy Docker Method.
2. Tried exporting my signal data.
3. I have tried pagination (50, 100, 200) and no pagination; all result in the same error.
4. output with verbose:
[Terminal Saved Output copy.txt](https://github.com/carderne/signal-export/files/9217131/Terminal.Saved.Output.copy.txt)

heads up: I am an extreme newbie, I have never touched any code nor do I know what any of this means; I just want to backup my signal data because it is very very very important to me. And I really appreciate everyone in this community working on third party tools to enable this

**Comment by carderne** [comment]
Hi @reludy. There seems to be some issue with converting the Markdown to HTML.

FYI it will still have successfully export the `.md` Markdown files, which you should find in the output directory. If you want, you can add the `--no-html` flag (just added in https://github.com/carderne/signal-export/commit/b1972bbc8be9b0dfe5bd135a1f7a163995d81eb1) and you won't get any errors.

**Comment by reludy** [comment]
I can't thank you enough! Whatever you did helped tremendously.

- I ran it again with verbose, and somehow got no errors at all except a few broken attachments. 
- I now have a 51 MB html file, and a 13 MB markdown file. 

Other issues (I wonder if I should open new issues for these here?):

1. signal-export manages to export all messages and media from May 1st to present day. This behavior was the same two weeks ago, the export started from May 1st. However, my conversation starts on April 30th.

2. Opening the html file completely crashes my MacBook and leaves it fully unresponsive. I assumed the media folder was at fault since it is 9 GB, so renaming it remedies the problem. What do you think?

**Comment by carderne** [comment]
Great!

1. Do the April 30th messages show up in Signal desktop?
2. I'm not surprised it doesn't work. Only solution would be to do the pagination via actually separate HTML files (right now it's just some trickery). I will keep this open as a reminder, but probably won't get to it any time soon.

**Comment by reludy** [comment]
1. Yes, April 30th messages do not show up, I'm dumb.
2. Okay gotcha. 

Thank you again @carderne. You have been a lifesaver!
