### ISSUE TITLE
Encoding errors

### ISSUE THREAD

**Issue by larrachecoeur** [carderne/signal-export#72]
**Desktop**
 - OS and version:  Windows 10
- Terminal/shell used: PowerShell

I am getting lots of encoding errors

e.g.

`
class IncrementalEncoder(codecs.IncrementalEncoder):                                       │
│    18 │   def encode(self, input, final=False):                                                  │
│ >  19 │   │   return codecs.charmap_encode(input,self.errors,encoding_table)[0]                  │
│    20                                                                                            │
│    21 class IncrementalDecoder(codecs.IncrementalDecoder):                                       │
│    22 │   def decode(self, input, final=False):                                                  │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │ final = False                                                                                │ │
│ │ input = "[2022-07-19 15:25] Me: Et si tu n′existais pas\r\nDis-moi pourquoi                  │ │
│ │         j'existerais\r\nP"+73                                                                │ │
│ │  self = <encodings.cp1252.IncrementalEncoder object at 0x000002942D3CAB00>                   │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
UnicodeEncodeError: 'charmap' codec can't encode character '\u2032' in position 33: character maps to <undefined>

chars with accents will not be mapped correctly, too. even their do not initiate an runtime error

�tre seul cet apr�s-midi
`

**Comment by carderne** [comment]
If you can try to track down the line in `sigexport/main.py` where this is happening then I can do a better job of helping! It should be somewhere in the error output.

**Comment by carderne** [comment]
Should be fixed by #80
