### ISSUE TITLE
docker returned non-zero exit status 125

### ISSUE THREAD

**Issue by TheElderBug** [carderne/signal-export#75]
Hello

**Desktop :**
- OS and version: [Parrot 5]
- Terminal/shell used: [bash]

I tried to do the installation with and without the Doker. But as I understand, it is used anyway.
The program is started with the following command:
`sigexport ./output --source ./DirWithSQLDirAndConfigJSON`

After a few seconds I get the following error:
`Docker process failed, see logs below
command '['docker','run','-rm','--volume=MyDir:/Signal','carderne/sigexport:latest']' 
returned non-zero exit status 125`

I don't know whether it is important or not, but I use the internet with proxy.
Thanks, I hope for your help!

**Comment by carderne** [comment]
Try running that command in the terminal and see what happens.
```bash
docker run --rm --pull=always --volume MyDir:/Signal carderne/sigexport:latest
```

**Comment by Aponya** [comment]
Thanks for the answer
I won't have access to a computer with a signal until Monday. I will definitely try your advice and write an answer.
It's just strange that no one but me has ever encountered this problem.

**Comment by Aponya** [comment]
I get proxychains error: connection refused

**Comment by Aponya** [comment]
Is there a method for usage your project without Docker?

**Comment by carderne** [comment]
> I get proxychains error: connection refused

No idea what this means, and Google isn’t very helpful. Try this:
```
docker run hello-world
```

That will presumably give the same error and confirm that there is something wrong with your Docker installation and you’ll need to figure that out.

**Comment by carderne** [comment]
> Is there a method for usage your project without Docker?

[Yes](https://github.com/carderne/signal-export#alternative-installation-method)

**Comment by Aponya** [comment]
i did it for debian, but it still works with docker

**Comment by marcusquinn** [comment]
Updating Docker to latest fixed for me
