### ISSUE TITLE
Ability to export a backup file that can be reimported into signal on mobile

### ISSUE THREAD

**Issue by da5nsy** [carderne/signal-export#77]
**Is your feature request related to a problem? Please describe.**
I lost my phone.
I still have Signal on desktop.

**Describe the solution you'd like**
I'd like to be able to export my data from Signal desktop, and then import that data when setting up my new phone.

---

My understanding is that this project currently exports the data as markdown/html files which cannot be re-imported into Signal.
Please (oh god please) tell me if there is already a simple way to do this (either officially, with this project, or with another project).

**Comment by carderne** [comment]
Yeah sorry don’t think it’s possible… at least not on iOS, might be something on Android but either way this tool won’t help.

**Comment by da5nsy** [comment]
I am on android. Do you know of any tools that you could point me towards?

**Comment by carderne** [comment]
There are two linked here: https://github.com/carderne/signal-export#similar-things
