### ISSUE TITLE
All the attachment files are broken and cannot be opened

### ISSUE THREAD

**Issue by noahjgente** [carderne/signal-export#85]
**Setup:**
I am on Lubuntu 20.04 and have installed Signal as a snap in version 5.63.0. I installed signal-export using the docker method according to the Readme. 

**What I did**
I ran the export using

`sigexport --source /home/myusername/snap/signal-desktop/current/.config/Signal /path-for-export`

Note: Because of https://github.com/carderne/signal-export/issues/83 the export aborted at a point where some attachments were exported and some not. Because of https://github.com/carderne/signal-export/issues/84 I cannot currently retry it with the fixed version. Yesterday I ran the application locally though with a fix of https://github.com/carderne/signal-export/issues/83 and I had the same problem. So the problem seems unrelated to the mentioned issues. 

**Bug**
There are downloaded attachments in the media folder of each chat. They have meaningful names and they are not empty - they seem to have reasonable file sizes. However they don't seem to be valid files. When I try to open them I get unspecific error messages from the respective editors. ("Could not open file" etc.) I tried this for JPEG images, pdf documents, as well as audio files. 

Let me know if there is more information I can provide to make it reproducible.

**Comment by carderne** [comment]
1. I forgot to bump the version. Try `pip install --upgrade signal-export` and see if it persists.

2. This sounds (maybe?) like a file permissions error from Docker...? Could you try something like `ls -l /path/to/attachments` and see who it reports as the user/group? You could also just `sudo chown -R $USER /path/to/attachments` and see if that helps at all.

**Comment by noahjgente** [comment]
You were right, it was a permission problem, that occurred when I ran the docker container locally. The files were owned by root. After running it again with the pip version it worked fine! :tada:
