### ISSUE TITLE
All reactions from my own account are shown as "None"

### ISSUE THREAD

**Issue by noahjgente** [carderne/signal-export#86]
**Setup:**
I am on Lubuntu 20.04 and have installed Signal as a snap in version 5.63.0. I installed signal-export using the docker method according to the Readme.

**What I did**
I ran the export using

sigexport --source /home/myusername/snap/signal-desktop/current/.config/Signal /path-for-export

**Bug**
In the resulting html my reactions to messages are not shown with the correct name. 
Every message that I reacted to shows "None" as the username of the person that reacted to the message. 

**Update**
Actually I just realized that I do not have a name on signal, that might be the reason for the issue. In that case this is more of a feature request to show "Me" as the name for the reaction to messages.

**Comment by carderne** [comment]
The relevant code is here: https://github.com/carderne/signal-export/blob/3a7c26742d9bdcf8de8be86fc66764262a50c3da/sigexport/main.py#L194-L207

It uses `r["fromId"]` as a key for the `contacts` dict. Should be a way to see whether that item refers to "Me" and replace it in that case. Feel free to have a play around with a `breakpoint()` in that loop and see what you can figure out!
