### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by dmct10** [carderne/signal-export#89]
Non-dev here. I have installed Python, Anaconda. Not sure what I'm doing wrong here.

when I pull and run carderne/sigexport:latest

I get the error 

2022-11-21 09:59:36 Error: /Signal/config.json not found in directory /Signal

I do not know how to do this:

> Then run the script! It will do some Docker stuff under the hood to get your data out of the encrypted database.
> 
> sigexport ~/signal-chats
> # output will be saved to the supplied directory

Run the script in what? How? Sorry, I'm just a normal Signal user trying to back some stuff up.

**Comment by carderne** [comment]
Can you clarify what exactly you did? Did you run `sigexport output-folder-name` in Powershell, or run the image in Docker Desktop, or something else?

The error you got means that the docker image couldn't find any data, so probably the script didn't provide it correctly, or you didn't. It's also possible that there isn't any data there, so check for a file called `config.json` under `AppData/Roaming/Signal` in your home directory.

**Comment by dmct10** [comment]
I installed Docker, then pulled the 200MB file. When I ran the image, I received the error, but it looks like there is indeed a config.json in AppData\Roaming\Signal.

When I run sigexport output-folder-name in PowerShell, I receive:

sigexport : The term 'sigexport' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ sigexport output-folder-name
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (sigexport:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by carderne** [comment]
### The direct Docker method
In Docker, you're trying to run it without Python.
See the instructions [here](https://github.com/carderne/signal-export#usage-without-python).
The way you actually run this in Docker Desktop might be different.
(But not that you must provide the two volume mounts `-v $BLABLA:/Signal` etc, and you must add the `--overwrite /output` argument.)

### With Python
It sounds like you haven't installed the package. Did you run `pip install signal-export`?

**Comment by dmct10** [comment]
I'm sorry I am not following much of this.

I have Python installed. I have Docker installed. 

When I run "pip install signal-export" in Powershell, I receive a list of "Requirement already satisfied."

Then I run sigexport ~/signal-chats and receive this:

> sigexport : The term 'sigexport' is not recognized as the name of a cmdlet, function, script file, or operable
> program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + sigexport ~/signal-chats
> + ~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (sigexport:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

**Comment by dmct10** [comment]
And how do I provide the volume mounts?

**Comment by carderne** [comment]
Confirmation fmro #90 that the python command above will solve this. Also advice added to README in https://github.com/carderne/signal-export/commit/a4b250b8627fdebff8931e3748b9b366448e0c7c

**Comment by cloudgreen** [comment]
@dmct10 Did you manage to get this installed and working on Windows?

If I understand correctly, you should be able to do the export with just the following 3 steps on native Windows:

1) Install Docker Desktop and the sigexport image
2) Install Python and the signal-export script/package
3) Run the python script for export and the Python script will utilize the Docker image to do its magic

Did I get that correct? And no WSL needed?

**Comment by carderne** [comment]
Yes that should be possible! Please report back :)

**Comment by cloudgreen** [comment]
> Yes that should be possible! Please report back :)

Woho, it worked! :D Thanks for your great work! Images, videos and audio all work, very impressive.

I will try to summarize Windows installation instructions, if it would be of help.

**Comment by dmct10** [comment]
@cloudgreen 

Sorry, this was five months ago and I'm not sure how to get back to where you need me to go. The instructions were too unclear and I abandoned my attempt.

**Comment by dmct10** [comment]
PS C:\Users\ABC> python -m sigexport.main ~/signal-chats
Using Docker to extract data, this may take a while the first time!
Exception in thread Thread-2 (_readerthread):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1499, in _readerthread
    buffer.append(fh.read())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1739: character maps to <undefined>
Docker process failed, see logs below:
Command '['docker', 'run', '--rm', '--volume=C:\\Users\\ABC\\AppData\\Roaming\\Signal:/Signal', 'carderne/sigexport:v1.5.3']' returned non-zero exit status 1.

**Comment by cloudgreen** [comment]
> @cloudgreen
> 
> Sorry, this was five months ago and I'm not sure how to get back to where you need me to go. The instructions were too unclear and I abandoned my attempt.

Thanks for getting back! I actually managed to get it working myself, and will try to write some clear Windows installation instructions soon!

**Comment by Yolakalemowa** [comment]
> > @cloudgreen
> > Sorry, this was five months ago and I'm not sure how to get back to where you need me to go. The instructions were too unclear and I abandoned my attempt.
> 
> Thanks for getting back! I actually managed to get it working myself, and will try to write some clear Windows installation instructions soon!

Hi... I thought I'd check if you wrote this windows installation? Would be really appreciated.

**Comment by carderne** [comment]
I have added these instructions here:
https://github.com/carderne/signal-export/?tab=readme-ov-file#-installation-windows

PRs improving these and adding links etc will be welcome.

**Comment by carderne** [comment]
What do you mean by "Download docker image"? Download the [sigexport](https://hub.docker.com/r/carderne/sigexport) Docker image? That should happen automatically when you run `sigexport ...`

**Comment by Yolakalemowa** [comment]
Hello and thanks for including windows instructions.

I think it could be simplified more tbh esp. for noob users like myself. I had to get help from the awesome community at PrivacyGuides.

For example: "1- Enable Windows WSL2 feature" (how exactly to enable it, step by step)

thanks again for a life-saver tool friend.

**Comment by carderne** [comment]
@cloudgreen if you want to contribute full, beginner-friendly instructions, please add them to the [new stub file INSTALLATION.md](https://github.com/carderne/signal-export/blob/main/INSTALLATION.md).

and you can the [link to that file](https://github.com/carderne/signal-export/blob/1df798588f0230bfc9a162eb61a77fd24b8c7f08/README.md?plain=1#L24) from the main README.

**Comment by dmct10** [comment]
I've spent about 10 hours trying to get this to work on Windows. No dice.
If anyone has detailed, verified instructions, please send me a DM.
ᐧ
