### ISSUE TITLE
signexport tries to use docker even with no-use-docker option

### ISSUE THREAD

**Issue by dstei** [carderne/signal-export#91]
I followed the No-Docker install how-to on Linux Mint 20.3 Cinnamon, but sigexport started from commandline exits with the following message (with or without --no-use-docker option, which should be default anyway according to --help):
```
sigexport --no-use-docker  ~/signal-chats

Using Docker to extract data, this may take a while the first time!
Error: using Docker method, but is Docker installed?
Try running this from the command line:
docker run hello-world
```
Is this to be expected and I need to install Docker anyway?

**Comment by carderne** [comment]
If the sqlcipher dependencies aren’t installed properly, it will fall back to trying to use Docker. Probably need to provide a warning message here: https://github.com/carderne/signal-export/blob/140777bd881e0c44743960ff2968145adcb07c53/sigexport/main.py#L520

A PR would be great if you have the time, no pressure though.

**Comment by dstei** [comment]
In fact, I just had to run `ldconfig` for python to find `libsqlcipher.so.0`, now it worked smoothly without docker :)

**Comment by carderne** [comment]
If there's something that could be clarified in the README I'd appreciate a pointer :)

**Comment by mcint** [comment]
It's easier to work through these errors if it explicitly reports that it's falling back. I've solved the library issues on previous versions. I'm on macOS, so ldconfig is not how libraries are configured.

I'm also getting Missing DEST arguments, from the arguments passed inside docker.

**Comment by carderne** [comment]
Good point.
Fixed here:
https://github.com/carderne/signal-export/commit/ca0e9a9e963e0b745a9e6bc219a89b930e27c63d

**Comment by abadstart** [comment]
@dstei 

> In fact, I just had to run `ldconfig` for python to find `libsqlcipher.so.0`, now it worked smoothly without docker :)

I'm sorry, but I don't know what that means. What exactly did you do to solve the issue? Tnx
