### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'C:\\Users\\genericuser2\\signal-chats\\USER2\\media\\2022-08-05T09-19-21.489_00_|_Walmart.pdf'

### ISSUE THREAD

**Issue by walterbax** [carderne/signal-export#93]
- OS and version: 
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.2604

- Terminal/shell used: PowerShell

ran:
python -m sigexport.main -o ~/signal-chats

errors after exporting a few attachments with the following:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\genericuser2\\signal-chats\\USER2\\media\\2022-08-05T09-19-21.489_00_|_Walmart.pdf'

I'm guessing to reproduce, have a file that has a | in it. and try and export.

**Comment by carderne** [comment]
Sorry for taking so long to get to this.
Just tried this and on macOS I'm unable to reproduce, so must be Windows-specific.

I've just made a [change](https://github.com/carderne/signal-export/commit/a98b6d32d9ffde8c1a88775e7f892a7ded928050) that should fix this, please try again, but first `pip install signal-export==1.5.5`. And if it still doesn't work, please share some more detail from the error (looking for the line in `main.py` where the error happened!).
