### ISSUE TITLE
Docker container chat export failes silently when chat name contains ampersand character.

### ISSUE THREAD

**Issue by ecarlseen** [carderne/signal-export#94]
**Desktop (please complete the following information):**
 - OS and version: macOS Ventura 13.2.1 (22D68)
 - Docker version: Docker 4.17.0 (engine 20.10.23)
- Terminal/shell used: bash 3.2
- CPU: 2.4 GHz 8-Core Intel Core i9
- RAM: 32 GB

**Describe the bug**
Running the Docker image when the chat group name contains an ampersand character ('&') causes the export to silently fail. Chat group names without ampersand characters export as expected.

**To reproduce**
Steps to reproduce the behavior. Please include the exact commands tried.
Run these commands:

```
SIGNAL_INPUT='/Users/test/Library/Application Support/Signal'
SIGNAL_OUTPUT='/Users/test/Output/Test'

docker run --rm   -v "$SIGNAL_INPUT:/Signal"   -v "$SIGNAL_OUTPUT:/output"  carderne/sigexport:latest  --overwrite /output --chats='Person 1 & Person 2'
```

Output is:

```
Copying and renaming attachments
Creating markdown files
Creating HTML files
Done!
```

However, no files are created.

**Comment by ecarlseen** [comment]
Going through the code, it looks like the "fix_names" function deals with emojis, but not other filename-unsafe characters. I would suggest removing the following:
`! @ & * ? / \ |`

**Comment by carderne** [comment]
Just tried this and not able to reproduce, my group with an `&` in it gets exported as normal.

Does everything work for you for a different group/contact with the ampersand?
