### ISSUE TITLE
What to do, if pip install command gives an error on Debian

### ISSUE THREAD

**Issue by elvisef** [carderne/signal-export#95]
**Desktop (please complete the following information):**
- Debian 11
- mate_terminal / bash

**Describe the bug**
While trying to run `pip install -e .[dev,sql]` I'm given an error/note like:

> ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/hackme/Pobrane/git/signal-export
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

![2023-03-06_09-27](https://user-images.githubusercontent.com/25976749/223056772-bd2a9cff-0dab-4e68-9510-4d214392a673.png)

**To reproduce**
Steps to reproduce the behavior. Please include the exact commands tried.
Just run the step (for linux) with the command `pip install -e .[dev,sql]`.

Does someone know what to do or how to fix this ?
Is this a missing component/requirement ?

PIP version
`pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)`

Python 3 version
`Python 3.9.2`

What's more, after running `pip install signal-export[sql]` the effect is:
![2023-03-06_09-38](https://user-images.githubusercontent.com/25976749/223059170-e918fd2b-e49b-453b-8417-9682076dde8e.png)

**Comment by carderne** [comment]
Editable install: you need pip >= 21.3.

No SQL: Try this: `pip install 'signal-export[sql]==1.5.5'`

**Comment by elvisef** [comment]
> Editable install: you [need](https://stackoverflow.com/questions/69711606/how-to-install-a-package-using-pip-in-editable-mode-with-pyproject-toml) pip >= 21.3.

Thanks, worked - now I have 23.x version

> No SQL: Try this: pip install 'signal-export[sql]==1.5.5'

This worked as well but... there is a "yellow" text while running it. 
Is there something wring ?
![2023-03-06_10-53](https://user-images.githubusercontent.com/25976749/223076492-1f387ae0-2d62-40e1-b189-13a754ea97e0.png)

**Comment by carderne** [comment]
It should be fine. It tried to install `pysqlcipher3` one way, failed, and so tried another way.

Whether `pysqlcipher3` will actually work is another question.
