### ISSUE TITLE
Command pip not found

### ISSUE THREAD

**Issue by floretessobreelmaigmo** [carderne/signal-export#98]
**Desktop (please complete the following information):**
 - OS and version: [e.g. Ubuntu 22.04, Windows 10, WSL 2]
- Terminal/shell used: [e.g. Ubuntu, PowerShell and CMD]

**Describe the bug**
after installing Docker and following all instructions, including post-installation steps, I get Command 'pip' not found, but can be installed with:
sudo apt install python3-pip

after trying that other command, I get

Package python3-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-pip' has no installation candidate

**To reproduce**
Steps to reproduce the behavior. Please include the exact commands tried.
1. Install Docker
2. Follow all steps
3. Install python
4. Reboot
5. pip install signal-export
6. Command 'pip' not found, but can be installed with:
sudo apt install python3-pip
7. sudo apt install python3-pip
8. Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python3-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-pip' has no installation candidate

If trying with PowerShell:
1. pip install signal-export
2. term 'pip' not recognize

If trying with cmd:
1. pip install signal-export
2. 'pip' not recognized

Sorry if I'm doing something stupid, I'm not used to any programming stuff

**Comment by carderne** [comment]
Sorry I can't help on the pip installation issue, it can be frustrating if you're not familiar with Python/LInux.

I'd suggest you try the [No-Python Install](https://github.com/carderne/signal-export#-no-python-install) method.

**Comment by floretessobreelmaigmo** [comment]
Hi. I finally managed to solve it and install it by updating Python. However, when I try to use it I get
`Error: /home/user/.config/Signal/config.json not found in directory /home/user/.config/Signal`
Any way to solve this?
Thanks in advance
