### ISSUE TITLE
Error: /Signal/config.json not found in directory /Signal

### ISSUE THREAD

**Issue by BrownSim** [carderne/signal-export#99]
**Desktop:**
 - Macos Monterey
- Terminal (Macos basic)

**To reproduce**
1 download the image with docker pull carderne/sigexport cmd (or use the macos docker desktop)
2 start it and I have this issue 

thx

**Comment by BrownSim** [comment]
Sry my bad

**Comment by weirdmustard** [comment]
Please, how did you solve this?
